name: flutter_app_hyuabot_v2
description: flutter-app-hyuabot

publish_to: 'none'
version: 0.3.2+34

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  settings_ui: ^0.4.0
  http: ^0.12.2
  sqflite: ^1.3.0
  path: ^1.7.0
  url_launcher: ^5.7.10
  firebase_messaging: ^7.0.3
  flutter_native_admob: ^2.1.0+3
  naver_map_plugin: ^0.9.0
  firebase_core: 0.5.3
  firebase_analytics: ^6.3.0
  flutter_local_notifications: ^3.0.2
  flutter_material_pickers: ^1.9.1
  material_floating_search_bar: ^0.2.6
  syncfusion_flutter_calendar: ^18.4.33
  double_back_to_close_app: ^1.2.0
  fluttertoast: ^7.1.6
  shared_preferences: ^0.5.12+4
  easy_localization: ^2.3.3
  adaptive_theme: ^1.1.0
  rxdart: ^0.25.0
  transition: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/launcher/
    - assets/images/
    - assets/databases/
    - assets/translations/
  fonts:
    - family: Godo
      fonts:
        - asset: fonts/GodoM.otf
        - asset: fonts/GodoB.otf
