name: flutter_app_hyuabot_v2
description: flutter-app-hyuabot-v2

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get: ^3.17.1
  settings_ui: ^0.4.0
  shared_preferences: ^0.5.12+2
  rxdart: ^0.24.1
  http: ^0.12.2
  sqflite: ^1.3.0
  path: ^1.7.0
  url_launcher: ^5.7.10
  percent_indicator: ^2.1.8
  adaptive_theme: ^1.1.0
  flutter_phoenix: ^0.1.0
  firebase_messaging: ^7.0.3
  flutter_native_admob: ^2.1.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/launcher/
    - assets/images/
