name: flutter_app_hyuabot_v2
description: flutter-app-hyuabot

publish_to: 'none'
version: 0.5.0+50

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_native_splash: ^1.0.3


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.0
  settings_ui: ^1.0.0-nullsafety.2
  http: ^0.13.1
  sqflite: ^2.0.0+3
  path: ^1.8.0
  url_launcher: ^6.0.3
  firebase_messaging: ^9.1.1
  native_admob_flutter: ^1.2.0
  naver_map_plugin: ^0.9.5
  firebase_core: ^1.0.3
  flutter_local_notifications: ^5.0.0+1
  flutter_material_pickers: ^2.1.0
  material_floating_search_bar: ^0.3.3
  syncfusion_flutter_calendar: ^19.1.56
  double_back_to_close_app: ^2.0.1
  fluttertoast: ^8.0.3
  shared_preferences: ^2.0.5
  easy_localization: ^3.0.0
  adaptive_theme: ^2.1.1
  rxdart: ^0.26.0
  transition: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/launcher/
    - assets/images/
    - assets/databases/
    - assets/translations/
  fonts:
    - family: Godo
      fonts:
        - asset: fonts/GodoM.otf
        - asset: fonts/GodoB.otf

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/images/hanyang-phone.png
  fullscreen: true