name: flutter_app_hyuabot_v2
description: flutter-app-hyuabot

publish_to: 'none'
version: 0.1.3+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get: ^3.17.1
  settings_ui: ^0.4.0
  shared_preferences: 0.5.12+4
  rxdart: ^0.24.1
  http: ^0.12.2
  sqflite: ^1.3.0
  path: ^1.7.0
  url_launcher: ^5.7.10
  adaptive_theme: ^1.1.0
  flutter_phoenix: ^0.1.0
  firebase_messaging: ^7.0.3
  flutter_native_admob: ^2.1.0+3
  fluttertoast: ^7.1.6
  naver_map_plugin: ^0.9.0
  firebase_core: 0.5.3
  firebase_analytics: ^6.3.0
  cloud_firestore: ^0.14.4
  modal_bottom_sheet: ^1.0.0+1
  flutter_point_tab_bar: 0.1.0
  flutter_local_notifications: ^3.0.2
  flutter_picker: ^1.1.5
  material_floating_search_bar: ^0.2.6
  syncfusion_flutter_calendar: ^18.4.33


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/launcher/
    - assets/images/
    - assets/locale/
    - assets/databases/
  fonts:
    - family: Godo
      fonts:
        - asset: fonts/GodoM.otf
        - asset: fonts/GodoB.otf
