name: flutter_app_hyuabot_v2
description: flutter-app-hyuabot

publish_to: 'none'
version: 0.2.7+27

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  get: ^3.17.1
  get_storage: ^1.4.0
  settings_ui: ^0.4.0
  http: ^0.12.2
  sqflite: ^1.3.0
  path: ^1.7.0
  url_launcher: ^5.7.10
  adaptive_theme: ^1.1.0
  firebase_messaging: ^7.0.3
  flutter_native_admob: ^2.1.0+3
  naver_map_plugin: ^0.9.0
  firebase_core: 0.5.3
  firebase_analytics: ^6.3.0
  flutter_point_tab_bar: 0.1.0
  flutter_local_notifications: ^3.0.2
  flutter_picker: ^1.1.5
  material_floating_search_bar: ^0.2.6
  syncfusion_flutter_calendar: ^18.4.33
  double_back_to_close_app: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/launcher/
    - assets/images/
    - assets/databases/
  fonts:
    - family: Godo
      fonts:
        - asset: fonts/GodoM.otf
        - asset: fonts/GodoB.otf
