name: flutter_app_hyuabot_v2
description: flutter-app-hyuabot

publish_to: 'none'
version: 0.3.6+38

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  flutter_native_splash: ^1.0.3

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  timezone: ^0.7.0-nullsafety.0
  file_picker: '>=2.0.0 <3.0.0-nullsafety.0'
  plugin_platform_interface: ^2.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  cupertino_icons: ^1.0.0
  settings_ui: ^0.6.0
  http: ^0.13.0
  sqflite: ^2.0.0+2
  path: ^1.8.0
  url_launcher: ^6.0.2
  firebase_messaging: ^9.0.0
  flutter_native_admob: ^2.1.0+3
  naver_map_plugin: ^0.9.5
  firebase_core: ^1.0.0
  flutter_local_notifications: ^5.0.0-nullsafety.0
  flutter_material_pickers: ^1.9.2
  material_floating_search_bar: ^0.2.6
  syncfusion_flutter_calendar: ^18.4.46
  double_back_to_close_app: ^2.0.1
  fluttertoast: ^7.1.8
  shared_preferences: ^2.0.3
  easy_localization: ^3.0.0
  adaptive_theme: ^2.0.0-nullsafety.1
  rxdart: ^0.26.0
  transition: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/launcher/
    - assets/images/
    - assets/databases/
    - assets/translations/
  fonts:
    - family: Godo
      fonts:
        - asset: fonts/GodoM.otf
        - asset: fonts/GodoB.otf

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/images/hanyang-phone.png
  fullscreen: true